# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Xilinx/PLD/pld-repo/projects/main/main.srcs/sources_1/ip/bicubic_raw_cache/bicubic_raw_cache.xci
# IP: The module: 'bicubic_raw_cache' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/bicubic_raw_cache/bicubic_raw_cache.xdc
# XDC: The top module name and the constraint reference have the same name: 'bicubic_raw_cache'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/bicubic_raw_cache/bicubic_raw_cache_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bicubic_raw_cache'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/bicubic_raw_cache/bicubic_raw_cache_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bicubic_raw_cache'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Xilinx/PLD/pld-repo/projects/main/main.srcs/sources_1/ip/bicubic_raw_cache/bicubic_raw_cache.xci
# IP: The module: 'bicubic_raw_cache' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/bicubic_raw_cache/bicubic_raw_cache.xdc
# XDC: The top module name and the constraint reference have the same name: 'bicubic_raw_cache'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/bicubic_raw_cache/bicubic_raw_cache_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bicubic_raw_cache'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/bicubic_raw_cache/bicubic_raw_cache_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bicubic_raw_cache'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
