#sys_clk and rst
set_property IOSTANDARD LVCMOS33 [get_ports i_soc_clk]
set_property PACKAGE_PIN W19 [get_ports i_soc_clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_rstn]
set_property PACKAGE_PIN Y19 [get_ports i_rstn]

#摄像头
create_clock -period 11.905 -name camera_clock [get_ports i_camera_pclk]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_camera_pclk_IBUF]
set_property IOSTANDARD LVCMOS33 [get_ports i_camera_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports {i_camera_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_camera_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_camera_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_camera_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_camera_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_camera_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_camera_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_camera_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_camera_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports i_camera_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports o_camera_scl]
set_property IOSTANDARD LVCMOS33 [get_ports io_camera_sda]
set_property IOSTANDARD LVCMOS33 [get_ports o_camera_power_down]
set_property IOSTANDARD LVCMOS33 [get_ports o_camera_resetn]
set_property IOSTANDARD LVCMOS33 [get_ports o_camera_xclk]
set_property PACKAGE_PIN U20 [get_ports {i_camera_data[0]}]
set_property PACKAGE_PIN V20 [get_ports {i_camera_data[1]}]
set_property PACKAGE_PIN AB21 [get_ports {i_camera_data[2]}]
set_property PACKAGE_PIN AB22 [get_ports {i_camera_data[3]}]
set_property PACKAGE_PIN Y21 [get_ports {i_camera_data[4]}]
set_property PACKAGE_PIN Y22 [get_ports {i_camera_data[5]}]
set_property PACKAGE_PIN R18 [get_ports {i_camera_data[6]}]
set_property PACKAGE_PIN T18 [get_ports {i_camera_data[7]}]
set_property PACKAGE_PIN T21 [get_ports o_camera_scl]
set_property PACKAGE_PIN U21 [get_ports io_camera_sda]
set_property PACKAGE_PIN N15 [get_ports i_camera_vsync]
set_property PACKAGE_PIN U18 [get_ports i_camera_hsync]
set_property PACKAGE_PIN P17 [get_ports i_camera_pclk]
set_property PACKAGE_PIN U17 [get_ports o_camera_power_down]
set_property PACKAGE_PIN AB18 [get_ports o_camera_resetn]
set_property PACKAGE_PIN N17 [get_ports o_camera_xclk]




#hdmi_out
set_property PACKAGE_PIN F18 [get_ports {o_tmds_data_p[2]}]
set_property PACKAGE_PIN B15 [get_ports {o_tmds_data_p[1]}]
set_property PACKAGE_PIN E16 [get_ports {o_tmds_data_p[0]}]
set_property PACKAGE_PIN A13 [get_ports o_tmds_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports o_tmds_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports {o_tmds_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {o_tmds_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {o_tmds_data_p[0]}]

set_property PACKAGE_PIN M22 [get_ports init_calib_complete]
set_property IOSTANDARD LVCMOS33 [get_ports init_calib_complete]


set_property PACKAGE_PIN R16 [get_ports i_key1]
set_property IOSTANDARD LVCMOS33 [get_ports i_key1]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list video_system/memory_top/mig_inst/u_mig_7series_0_mig/u_ddr3_infrastructure/CLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {video_system/memory_top/camera_axi_write/wr_addr[0]} {video_system/memory_top/camera_axi_write/wr_addr[1]} {video_system/memory_top/camera_axi_write/wr_addr[2]} {video_system/memory_top/camera_axi_write/wr_addr[3]} {video_system/memory_top/camera_axi_write/wr_addr[4]} {video_system/memory_top/camera_axi_write/wr_addr[5]} {video_system/memory_top/camera_axi_write/wr_addr[6]} {video_system/memory_top/camera_axi_write/wr_addr[7]} {video_system/memory_top/camera_axi_write/wr_addr[8]} {video_system/memory_top/camera_axi_write/wr_addr[9]} {video_system/memory_top/camera_axi_write/wr_addr[10]} {video_system/memory_top/camera_axi_write/wr_addr[11]} {video_system/memory_top/camera_axi_write/wr_addr[12]} {video_system/memory_top/camera_axi_write/wr_addr[13]} {video_system/memory_top/camera_axi_write/wr_addr[14]} {video_system/memory_top/camera_axi_write/wr_addr[15]} {video_system/memory_top/camera_axi_write/wr_addr[16]} {video_system/memory_top/camera_axi_write/wr_addr[17]} {video_system/memory_top/camera_axi_write/wr_addr[18]} {video_system/memory_top/camera_axi_write/wr_addr[19]} {video_system/memory_top/camera_axi_write/wr_addr[20]} {video_system/memory_top/camera_axi_write/wr_addr[21]} {video_system/memory_top/camera_axi_write/wr_addr[22]} {video_system/memory_top/camera_axi_write/wr_addr[23]} {video_system/memory_top/camera_axi_write/wr_addr[24]} {video_system/memory_top/camera_axi_write/wr_addr[25]} {video_system/memory_top/camera_axi_write/wr_addr[26]} {video_system/memory_top/camera_axi_write/wr_addr[27]} {video_system/memory_top/camera_axi_write/wr_addr[28]} {video_system/memory_top/camera_axi_write/wr_addr[29]} {video_system/memory_top/camera_axi_write/wr_addr[30]} {video_system/memory_top/camera_axi_write/wr_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 7 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {video_system/memory_top/axi_read_m/video_fifo_cnt[0]} {video_system/memory_top/axi_read_m/video_fifo_cnt[1]} {video_system/memory_top/axi_read_m/video_fifo_cnt[2]} {video_system/memory_top/axi_read_m/video_fifo_cnt[3]} {video_system/memory_top/axi_read_m/video_fifo_cnt[4]} {video_system/memory_top/axi_read_m/video_fifo_cnt[5]} {video_system/memory_top/axi_read_m/video_fifo_cnt[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {video_system/memory_top/axi_read_m/M_AXI_ARADDR[0]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[1]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[2]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[3]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[4]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[5]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[6]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[7]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[8]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[9]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[10]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[11]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[12]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[13]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[14]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[15]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[16]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[17]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[18]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[19]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[20]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[21]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[22]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[23]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[24]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[25]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[26]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[27]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[28]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[29]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[30]} {video_system/memory_top/axi_read_m/M_AXI_ARADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {video_system/memory_top/axi_read_m/video_rd_addr[0]} {video_system/memory_top/axi_read_m/video_rd_addr[1]} {video_system/memory_top/axi_read_m/video_rd_addr[2]} {video_system/memory_top/axi_read_m/video_rd_addr[3]} {video_system/memory_top/axi_read_m/video_rd_addr[4]} {video_system/memory_top/axi_read_m/video_rd_addr[5]} {video_system/memory_top/axi_read_m/video_rd_addr[6]} {video_system/memory_top/axi_read_m/video_rd_addr[7]} {video_system/memory_top/axi_read_m/video_rd_addr[8]} {video_system/memory_top/axi_read_m/video_rd_addr[9]} {video_system/memory_top/axi_read_m/video_rd_addr[10]} {video_system/memory_top/axi_read_m/video_rd_addr[11]} {video_system/memory_top/axi_read_m/video_rd_addr[12]} {video_system/memory_top/axi_read_m/video_rd_addr[13]} {video_system/memory_top/axi_read_m/video_rd_addr[14]} {video_system/memory_top/axi_read_m/video_rd_addr[15]} {video_system/memory_top/axi_read_m/video_rd_addr[16]} {video_system/memory_top/axi_read_m/video_rd_addr[17]} {video_system/memory_top/axi_read_m/video_rd_addr[18]} {video_system/memory_top/axi_read_m/video_rd_addr[19]} {video_system/memory_top/axi_read_m/video_rd_addr[20]} {video_system/memory_top/axi_read_m/video_rd_addr[21]} {video_system/memory_top/axi_read_m/video_rd_addr[22]} {video_system/memory_top/axi_read_m/video_rd_addr[23]} {video_system/memory_top/axi_read_m/video_rd_addr[24]} {video_system/memory_top/axi_read_m/video_rd_addr[25]} {video_system/memory_top/axi_read_m/video_rd_addr[26]} {video_system/memory_top/axi_read_m/video_rd_addr[27]} {video_system/memory_top/axi_read_m/video_rd_addr[28]} {video_system/memory_top/axi_read_m/video_rd_addr[29]} {video_system/memory_top/axi_read_m/video_rd_addr[30]} {video_system/memory_top/axi_read_m/video_rd_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 10 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {video_system/memory_top/camera_axi_write/wr_cnt[0]} {video_system/memory_top/camera_axi_write/wr_cnt[1]} {video_system/memory_top/camera_axi_write/wr_cnt[2]} {video_system/memory_top/camera_axi_write/wr_cnt[3]} {video_system/memory_top/camera_axi_write/wr_cnt[4]} {video_system/memory_top/camera_axi_write/wr_cnt[5]} {video_system/memory_top/camera_axi_write/wr_cnt[6]} {video_system/memory_top/camera_axi_write/wr_cnt[7]} {video_system/memory_top/camera_axi_write/wr_cnt[8]} {video_system/memory_top/camera_axi_write/wr_cnt[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[0]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[1]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[2]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[3]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[4]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[5]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[6]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[7]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[8]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[9]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[10]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[11]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[12]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[13]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[14]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[15]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[16]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[17]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[18]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[19]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[20]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[21]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[22]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[23]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[24]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[25]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[26]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[27]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[28]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[29]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[30]} {video_system/memory_top/camera_axi_write/M_AXI_AWADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {video_system/memory_top/camera_axi_write/rd_data_count[0]} {video_system/memory_top/camera_axi_write/rd_data_count[1]} {video_system/memory_top/camera_axi_write/rd_data_count[2]} {video_system/memory_top/camera_axi_write/rd_data_count[3]} {video_system/memory_top/camera_axi_write/rd_data_count[4]} {video_system/memory_top/camera_axi_write/rd_data_count[5]} {video_system/memory_top/camera_axi_write/rd_data_count[6]} {video_system/memory_top/camera_axi_write/rd_data_count[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list video_system/memory_top/camera_axi_write/M_AXI_AWVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list video_system/memory_top/axi_read_m/M_AXI_RVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list video_system/memory_top/axi_read_m/video_fifo_full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list video_system/memory_top/axi_read_m/wr_rst_busy]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list video_system/video_sys_clk/inst/hdmi_pix]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 16 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {video_system/debug_cam/sim_data[0]} {video_system/debug_cam/sim_data[1]} {video_system/debug_cam/sim_data[2]} {video_system/debug_cam/sim_data[3]} {video_system/debug_cam/sim_data[4]} {video_system/debug_cam/sim_data[5]} {video_system/debug_cam/sim_data[6]} {video_system/debug_cam/sim_data[7]} {video_system/debug_cam/sim_data[8]} {video_system/debug_cam/sim_data[9]} {video_system/debug_cam/sim_data[10]} {video_system/debug_cam/sim_data[11]} {video_system/debug_cam/sim_data[12]} {video_system/debug_cam/sim_data[13]} {video_system/debug_cam/sim_data[14]} {video_system/debug_cam/sim_data[15]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 3 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {video_system/debug_cam/state_current[0]} {video_system/debug_cam/state_current[1]} {video_system/debug_cam/state_current[2]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list video_system/memory_top/camera_axi_write/cam_fifo_full]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list video_system/debug_cam/sim_data_wren]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list video_system/debug_cam/sim_vsync]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list video_system/memory_top/axi_read_m/video_fifo_empty]]
set_property PULLDOWN true [get_ports {i_camera_data[7]}]
set_property PULLDOWN true [get_ports {i_camera_data[6]}]
set_property PULLDOWN true [get_ports {i_camera_data[5]}]
set_property PULLDOWN true [get_ports {i_camera_data[4]}]
set_property PULLDOWN true [get_ports {i_camera_data[3]}]
set_property PULLDOWN true [get_ports {i_camera_data[2]}]
set_property PULLDOWN true [get_ports {i_camera_data[1]}]
set_property PULLDOWN true [get_ports {i_camera_data[0]}]
set_property PULLDOWN true [get_ports i_camera_pclk]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_CLK]
