# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx/PLD/pld-repo/projects/e203-zybo/e203-zybo.srcs/sources_1/ip/reset_sys/reset_sys.xci
# IP: The module: 'reset_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/PLD/pld-repo/projects/e203-zybo/e203-zybo.gen/sources_1/ip/reset_sys/reset_sys_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/e203-zybo/e203-zybo.gen/sources_1/ip/reset_sys/reset_sys.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/e203-zybo/e203-zybo.gen/sources_1/ip/reset_sys/reset_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Xilinx/PLD/pld-repo/projects/e203-zybo/e203-zybo.srcs/sources_1/ip/reset_sys/reset_sys.xci
# IP: The module: 'reset_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/PLD/pld-repo/projects/e203-zybo/e203-zybo.gen/sources_1/ip/reset_sys/reset_sys_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/e203-zybo/e203-zybo.gen/sources_1/ip/reset_sys/reset_sys.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/e203-zybo/e203-zybo.gen/sources_1/ip/reset_sys/reset_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'reset_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
