# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx/PLD/pld-repo/projects/main/main.srcs/sources_1/ip/sharpen2x_ram/sharpen2x_ram.xci
# IP: The module: 'sharpen2x_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/sharpen2x_ram/sharpen2x_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sharpen2x_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Xilinx/PLD/pld-repo/projects/main/main.srcs/sources_1/ip/sharpen2x_ram/sharpen2x_ram.xci
# IP: The module: 'sharpen2x_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/sharpen2x_ram/sharpen2x_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sharpen2x_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
