# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tfgg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core
    E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_i2c
    e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/clk_wiz_0
    e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/clk_wiz_1
    e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/mmcm
    e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/font_rom
  } {
      E:/Xilinx/Vivado/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      E:/Xilinx/Vivado/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core
    E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_i2c
    e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/clk_wiz_0
    e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/clk_wiz_1
    e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/mmcm
    e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/font_rom
  } {
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/video_rd_fifo_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/mig_7series_0_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/fifo_generator_0_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/clk_wiz_0_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/clk_wiz_1_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/bicubic_raw_cache_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/ui_ram_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/font_rom_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/mmcm_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/reset_sys_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/bicubic_2x_buffer_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/vpu_result_ram_stub.v
      E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/camera_wr_fifo_stub.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_defines.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/camera/Camera_Interface.v
      {E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/OV5640 Driver/Dependencies/Clock_V2.3/Clock_Interface.v}
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/HDMI_Interface.v
      {E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/OV5640 Driver/Dependencies/IIC_V2.0/IIC_Interface.v}
      {E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/OV5640 Driver/OV5640_Interface.v}
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_adv_timer/adv_timer_apb_if.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_adv_timer/apb_adv_timer.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_gpio/apb_gpio.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_i2c/apb_i2c.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_spi_master/apb_spi_master.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_uart/apb_uart.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/memc/axi_master_read.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/memc/axi_master_write.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/utils/bicubic/bicubic_core.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/proc/bicubic/bicubic_top.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/e203/clk-div-zynq.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_adv_timer/comparator.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/memc/ddr_streaming_top.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/debug/debug_sim_cam.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_biu.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_clk_ctrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_clkgate.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_core.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_cpu.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_cpu_top.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_dtcm_ctrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_dtcm_ram.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_alu.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_alu_bjp.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_alu_csrctrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_alu_dpath.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_alu_lsuagu.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_alu_muldiv.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_alu_rglr.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_branchslv.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_commit.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_csr.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_decode.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_disp.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_excp.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_longpwbck.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_nice.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_oitf.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_regfile.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_exu_wbck.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_ifu.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_ifu_ifetch.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_ifu_ift2icb.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_ifu_litebpu.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_ifu_minidec.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_irq_sync.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_itcm_ctrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_itcm_ram.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_lsu.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_lsu_ctrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_reset_ctrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/soc/e203_soc_top.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/core/e203_srams.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_clint.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_gfcm.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_hclkgen.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_hclkgen_rstsync.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_main.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_mems.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_nice_core.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_perips.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_plic.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_pll.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_pllclkdiv.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/subsys/e203_subsys_top.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/hdmi_timing_gen.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_i2c/i2c_master_bit_ctrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_i2c/i2c_master_byte_ctrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_adv_timer/input_stage.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_uart/io_generic_fifo.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_adv_timer/prescaler.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/general/sirv_1cyc_sram_ctrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_AsyncResetReg.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_AsyncResetRegVec.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_AsyncResetRegVec_1.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_AsyncResetRegVec_129.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_AsyncResetRegVec_36.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_DeglitchShiftRegister.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_LevelGateway.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_ResetCatchAndSync.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_ResetCatchAndSync_2.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_aon.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_aon_lclkgen_regs.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_aon_porrst.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_aon_top.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_aon_wrapper.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_clint.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_clint_top.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/debug/sirv_debug_csr.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/debug/sirv_debug_module.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/debug/sirv_debug_ram.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/debug/sirv_debug_rom.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_expl_axi_slv.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_flash_qspi.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_flash_qspi_top.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/general/sirv_gnrl_bufs.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/general/sirv_gnrl_dffs.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/general/sirv_gnrl_icbs.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/general/sirv_gnrl_ram.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_hclkgen_regs.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/fab/sirv_icb1to16_bus.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/fab/sirv_icb1to2_bus.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/fab/sirv_icb1to8_bus.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/debug/sirv_jtag_dtm.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_jtaggpioport.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/mems/sirv_mrom.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/mems/sirv_mrom_top.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_plic_man.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_plic_top.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_pmu.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_pmu_core.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_qspi_arbiter.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_qspi_fifo.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_qspi_media.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_qspi_physical.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_queue.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_queue_1.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_repeater_6.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_rtc.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/general/sirv_sim_ram.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_spi_flashmap.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/general/sirv_sram_icb_ctrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_tl_repeater_5.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_tlfragmenter_qspi_1.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_tlwidthwidget_qspi.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/sirv_wdog.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_spi_master/spi_master_apb_if.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_spi_master/spi_master_clkgen.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_spi_master/spi_master_controller.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_spi_master/spi_master_fifo.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_spi_master/spi_master_rx.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_spi_master/spi_master_tx.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/e203/system.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_adv_timer/timer_cntrl.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_adv_timer/timer_module.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_uart/uart_interrupt.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_uart/uart_rx.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_uart/uart_tx.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/disp/ui_renderer.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/e203/perips/apb_adv_timer/up_down_counter.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/video_generator.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/proc/video_proc_unit.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/video_sys.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/video/proc/vpu_ioregs.v
      E:/Xilinx/PLD/pld-repo/rtl-srcs/system/soc/sys_top.v
    }
      rt::read_vhdl -lib xpm E:/Xilinx/Vivado/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/realtime/sys_top_synth.xdc
    rt::sdcChecksum
    set rt::top sys_top
    rt::set_parameter incrementalOnCache "E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/refSynth"
    rt::set_parameter doIncremental true
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {E:/Xilinx/PLD/pld-repo/projects/main/main.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/Xilinx/PLD/pld-repo/projects/main/main.runs/synth_1/.Xil/Vivado-29236-Kasaki352/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    rt::close_pss_mem_watcher
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
