# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Xilinx/PLD/pld-repo/projects/main/main.srcs/sources_1/ip/mmcm/mmcm.xci
# IP: The module: 'mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/mmcm/mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/mmcm/mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/mmcm/mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Xilinx/PLD/pld-repo/projects/main/main.srcs/sources_1/ip/mmcm/mmcm.xci
# IP: The module: 'mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/mmcm/mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/mmcm/mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/mmcm/mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
