# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Xilinx/PLD/pld-repo/projects/main/main.srcs/sources_1/ip/video_rd_fifo/video_rd_fifo.xci
# IP: The module: 'video_rd_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/video_rd_fifo/video_rd_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_rd_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/video_rd_fifo/video_rd_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_rd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/video_rd_fifo/video_rd_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_rd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Xilinx/PLD/pld-repo/projects/main/main.srcs/sources_1/ip/video_rd_fifo/video_rd_fifo.xci
# IP: The module: 'video_rd_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/video_rd_fifo/video_rd_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_rd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/video_rd_fifo/video_rd_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_rd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/Xilinx/PLD/pld-repo/projects/main/main.gen/sources_1/ip/video_rd_fifo/video_rd_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'video_rd_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
