# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Xilinx/PLD/pld-repo/rtl-srcs/system/constr/soc.xdc

# IP: ip/camera_wr_fifo/camera_wr_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_wr_fifo || ORIG_REF_NAME==camera_wr_fifo} -quiet] -quiet
